[package]
name = "visgra_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
crossbeam-channel = "0.5.4"
cpal = "0.13.5"
anyhow = "1.0.57"
